[package]
name = "FinalProject"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[registry]

[dependencies]
csv = "1.1.6"
num = "0.1.0"
kmeans="0.2.0"

